/**
 * COS-928 — keep PHI out of Android's backup channels, across prebuilds.
 *
 * ─── WHY THIS EXISTS, CONCRETELY ─────────────────────────────────────
 *
 * SCRUM-368 / MOBILE-002 hand-wrote `android:allowBackup="false"`,
 * `android:fullBackupContent="false"` and a `data_extraction_rules.xml`
 * excluding every domain, because AsyncStorage and SQLite in this app hold
 * PHI — demographics, encounters, observations, calendar events — and Android
 * Auto Backup copies app data to the user's Google Drive, which is outside our
 * BAA boundary (45 CFR 164.312(a)(2)(iv)).
 *
 * Those were hand edits to a generated file, and on 2026-09-07 a second
 * `expo prebuild -p android` silently replaced them. expo-secure-store ships a
 * config plugin that claims both attributes whenever they are absent:
 *
 *     android:fullBackupContent="@xml/secure_store_backup_rules"
 *     android:dataExtractionRules="@xml/secure_store_data_extraction_rules"
 *
 * and its rules are the OPPOSITE shape to ours — they INCLUDE app data and
 * exclude only SecureStore's own prefs:
 *
 *     <include domain="sharedpref" path="."/>
 *     <exclude domain="sharedpref" path="SecureStore"/>
 *
 * with nothing at all for the `database` or `file` domains. That is correct
 * for a normal app protecting its keychain, and wrong for ours, where the
 * database IS the sensitive thing.
 *
 * It survived the FIRST prebuild only by accident: our values were already
 * present, so secure-store's plugin logged a warning and deferred. On the
 * second, the directory was regenerated and it won.
 *
 * ─── WHY A PLUGIN AND NOT ANOTHER HAND EDIT ──────────────────────────
 *
 * A hand edit is one prebuild from being lost, and we now have direct evidence
 * of exactly that. app.json can express `allowBackup` (Expo has a plugin for
 * it) but NOT the two rules files, so this is the only place the full control
 * can live and survive.
 *
 * REGISTRATION ORDER IS LOAD-BEARING: this must come AFTER expo-secure-store
 * in app.json's `plugins` array. Plugins run in order and the last writer of a
 * manifest attribute wins. Listed last, so it also wins against anything added
 * later that tries to claim these attributes.
 *
 * ─── WHAT IT ENFORCES ────────────────────────────────────────────────
 *
 * Belt AND braces, deliberately, because they fail differently:
 *   allowBackup=false        — the master switch; comes from app.json.
 *   fullBackupContent        — Android 11 and lower.
 *   dataExtractionRules      — Android 12+ (cloud backup AND device transfer).
 *
 * Excluding domain="root" alone would be enough on paper; every domain is
 * listed explicitly because an empty rules file that LOOKS protective is worse
 * than none, and a future reader should be able to see the intent without
 * knowing Android's default-include semantics.
 */

const fs = require('fs');
const path = require('path');
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');

const RULES_NAME = 'data_extraction_rules';
const FULL_BACKUP_NAME = 'full_backup_rules';

const HEADER = `<!--
  GENERATED by plugins/withHipaaBackupRules.js — do not hand-edit.

  SCRUM-368 (MOBILE-002): exclude ALL app data from every Android backup
  channel. AsyncStorage / SQLite / SharedPreferences here may contain PHI, and
  the backup destination (Google Drive, or a device-to-device transfer) is
  outside our BAA boundary.

  Hand edits to this file are lost on the next \`expo prebuild\`. That is not
  hypothetical: it happened on 2026-09-07, when expo-secure-store's plugin
  claimed these attributes and substituted rules that INCLUDE app data.
-->`;

const DOMAINS = ['root', 'file', 'database', 'sharedpref', 'external'];
const excludes = (indent) => DOMAINS.map((d) => `${indent}<exclude domain="${d}" />`).join('\n');

const EXTRACTION_XML = `<?xml version="1.0" encoding="utf-8"?>
${HEADER}
<data-extraction-rules>
    <!-- Android 12+ : Google Drive / Auto Backup -->
    <cloud-backup>
${excludes('        ')}
    </cloud-backup>
    <!-- Android 12+ : direct device-to-device transfer -->
    <device-transfer>
${excludes('        ')}
    </device-transfer>
</data-extraction-rules>
`;

const FULL_BACKUP_XML = `<?xml version="1.0" encoding="utf-8"?>
${HEADER}
<!-- Android 11 and lower. Paired with android:allowBackup="false" so that
     even a device ignoring this file has backup switched off outright. -->
<full-backup-content>
${excludes('    ')}
</full-backup-content>
`;

module.exports = function withHipaaBackupRules(config) {
  // 1. Write both rules files into the app module's res/xml.
  config = withDangerousMod(config, [
    'android',
    (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, 'app/src/main/res/xml');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${RULES_NAME}.xml`), EXTRACTION_XML);
      fs.writeFileSync(path.join(dir, `${FULL_BACKUP_NAME}.xml`), FULL_BACKUP_XML);
      return cfg;
    },
  ]);

  // 2. Point the manifest at them, overriding whoever got there first.
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.$['android:allowBackup'] = 'false';
    app.$['android:fullBackupContent'] = `@xml/${FULL_BACKUP_NAME}`;
    app.$['android:dataExtractionRules'] = `@xml/${RULES_NAME}`;
    return cfg;
  });
};
